name: mulitple-event-workflow
on:
  push:
  issues:
      types: [opened]
      # 푸쉬, 이슈,수동 트리거에서도 작동
  workflow_dispatch:

jobs:
    mulitple-event-job:
        runs-on: ubuntu-latest
        steps:
            - name: mulitple event
              run: echo "hello world"
            - name: step2
              run: |
                echo hello world
                echo gihub action