  name: push-workflow
  on: push #push 이벤트가 발생할 때 workflow 실행

  jobs: # 잡 필수
    push-job:
      runs-on: ubuntu-latest # 실행 환경
      steps:
        - name: step1 # 단계 이름
          run: echo "hello world" # 실행할 명령어
        - name: step2
          run: | # 여러 줄의 명령어 실행
            echo "hello world2"
            echo "hello world3"