name: cicd-1
on:
    pull_request:
        types: [opened,synchronize,closed]  # PR이 열리거나 동기화되거나 닫힐 때 트리거
        branches: [dev] # dev 브랜치에서만 트리거
        paths:
        - 'my-app/**' # my-app 디렉토리에서만 트리거
jobs:
    test: # 테스트 작업
        if: github.event.action == 'opened' || github.event.action == 'synchronize'
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
    image-build: # 이미지 빌드 작업
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4
    deploy: # 배포 작업
        runs-on: ubuntu-latest  
        needs: [image-build]  # image-build 스텝이 성공적으로 완료되면 실행
        steps:
        - name: checkout
          uses: actions/checkout@v4