name: if-2
on: push
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: exit
          run: exit 1
        - name: echo
          if: always() # 항상 실행
          run: echo "job1"
    job2:
        needs: job1
        runs-on: ubuntu-latest
        if: always() # 항상 실행
        steps:
        - name: echo
          run: echo "job2"