name: artifact
on: push
jobs:
    upload-artifact:
        runs-on: ubuntu-latest
        steps:
            - name: echo
              uses: echo hello-world > hello.txt
            - name: upload artifact
              uses: actions/upload-artifact@v3 # artifact 업로드 액션 사용
              with:
                  name: artifact-test
                  paths: ./hello.txt

    download-artifact:
        needs: [upload-artifact] # upload-artifact 잡이 성공적으로 완료되어야만 실행
        runs-on: ubuntu-latest        
        steps:
            - name: download artifact
              uses: actions/download-artifact@v3 # artifact 다운로드 액션 사용
              with:
                  name: artifact-test
                  path: ./ # 현재 디렉토리에 다운로드
            - name: cat
              run: cat hello.txt