name: cicd-1
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - dev
    paths:
      - 'my-app/**'

jobs:
  test-job:
    if: github.event.action =='opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  image-build-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

  deplioy-job:
    needs: image-build-job
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4