name: cicd-2
on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - dev
      - master
    paths:
      - 'my-app/**'

jobs:
  test-job:
    if: github.event.action =='opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
#      - name: setup-node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 18
#      - name: Cache Node.js modules
#        uses: actions/cache@v3
#        with:
#          path: ~/.npm
#          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-node-
#      - name: Install dependencies
#        run: |
#          cd my-app
#          npm ci
#      - name: npm build
#        run: |
#          cd my-app
#          npm run build

  set-environment-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-env.outputs.environment }}
    steps:
      - name: set env
        id: set-env
        run: |
          echo ${{ github.base_ref }}
          echo "environment=dev" >> $GITHUB_OUTPUT
          
          if [[ ${{ github.base_ref }} == "master" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          fi
      - name: check env
        run: echo ${{ steps.set-env.outputs.environment }}

  image-build-job:
    needs: set-environment-job
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: ["${{ needs.set-environment-job.outputs.environment }}"]
    environment: ${{ matrix.environment }}
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
#      - name: Configure AWS Credentials
#        id: credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-region: ${{ vars.AWS_REGION }}
#          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#      - name: Login to Amazon ECR
#        id: login-ecr
#        uses: aws-actions/amazon-ecr-login@v2
#        with:
#          mask-password: 'true'
#      - name: docker build & push
#        run: |
#          docker build -f Dockerfile --tag ${{ secrets.REGISTRY }}/${{ vars.REPOSITORY }}:${{ github.sha }} .
#          docker push ${{ secrets.REGISTRY }}/${{ vars.REPOSITORY }}:${{ github.sha }}

  deploy-job:
    needs: [set-environment-job, image-build-job]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        environment: ["${{ needs.set-environment-job.outputs.environment }}"]
    environment: ${{ matrix.environment }}
    steps:
      - name: checkout the co=de
        uses: actions/checkout@v4
#      - name: Configure AWS Credentials
#        id: credentials
#        uses: aws-actions/configure-aws-credentials@v4
#        with:
#          aws-region: ${{ vars.AWS_REGION }}
#          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
#      - name: setup kubectl
#        uses: azure/setup-kubectl@v3
#        with:
#          version: 'latest'
#      - name: setup helm
#        uses: azure/setup-helm@v3
#        with:
#          version: 'latest'
#      - name: access kubernetes
#        run: |
#          aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }}
#      - name: deploy
#        id: status
#        run: |
#          helm upgrade --install my-app kubernetes/my-app --create-namespace --namespace my-app-${{ vars.SUFFIX }} \
#          --set image.tag=${{ github.sha }} \
#          --set image.repository=${{ secrets.REGISTRY }}/${{ vars.REPOSITORY }}
#      - name: notify
#        if: always()
#        uses: slackapi/slack-github-action@v2.1.1
#        with:
#          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
#          webhook-type: webhook-trigger
#          payload: |
#            {
#              "attachments": [
#                {
#                  "pretext": "message",
#                  "color": "28a745",
#                  "blocks": [
#                    {
#                      "type": "section",
#                      "text": {
#                                "type": "mrkdwn",
#                                "text": "Environment: dev, Deploy Result: ${{ needs.set-environment-job.outputs.environment }}, Repository: ${{ github.repository }} ."
#                              }
#                    }
#                  ]
#                }
#              ]
#            }

  create-pr-job:
    if: needs.set-environment-job.outputs.environment == 'dev'
    runs-on: ubuntu-latest
    needs: [set-environment-job, deploy-job]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: gh auth login
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | gh auth login --with-token
      - name: create branch
        run: |
          git checkout -b release/${{ github.run_id }}
          git push origin release/${{ github.run_id }}
      - name: create pr
        run: |
          gh pr create --base master --head release/${{ github.run_id }} --title "release/${{ github.run_id }} -> master" --body "release pr"