name: create-repo
on:
    workflow_dispatch:
        inputs:
            prefix:
                description: "set repo prefix"
                required: true # 필수 입력값라고 설정
                default: "service"
                type: choice
                options:
                - example
                - service

            name:
                description: "set repo name"
                required: true
                default: "github-actions"
                type: string
jobs:
    create-repo-automation:
        runs-on: ubuntu-latest
        steps:
        - name: gh auth login
          run: |
          echo ${{secrets.KEY}} | gh auth login --with-token
    # 토큰으로 로그인
        - name: create-repo
          run: |
            gh repo create gitchulsoo-action/${{inputs.prefix}}-${{inputs.name}} --public --add-readme
    # 퍼블릭 레포지토리 생성
