name: environment
on: push

jobs:
  get-env-job:
    runs-on: ubuntu-latest
    steps:
      - name: check env & secret
        run: |
          echo ${{ vars.level }}
          echo ${{ secrets.key }}

  get-env-dev-job:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: check env & secret
        run: |
          echo ${{ vars.level }}
          echo ${{ secrets.key }}