name: issue-notify
on:
  issues:
    types:
      - opened

jobs:
  get-keyword-job:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get keyword
        id: get-keyword
        run: |
          echo level=Undefined >> $GITHUB_OUTPUT
          
          keywords=$(cat keyword-list.txt)
          for keyword in $keywords; do
            if [[ "${{ github.event.issue.title }}" =~ "$keyword" ]]; then
              echo level=$keyword >> $GITHUB_OUTPUT
            fi
          done
      - name: get output
        run: |
          echo ${{ steps.get-keyword.outputs.level }}

  slack-job:
    needs: get-keyword-job
    if: needs.get-keyword-job.outputs.level != 'Undefined'
    runs-on: ubuntu-latest
#    environment: ${{ needs.get-keyword-job.outputs.level }}
    strategy:
      matrix:
        environment: ["${{ needs.get-keyword-job.outputs.level }}"]
    environment: ${{ matrix.environment }}
    steps:
      - name: slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: webhook-trigger
          payload: |
            {
              "attachments": [
                {
                  "pretext": "issue alert message",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Level: ${{ needs.get-keyword-job.outputs.level }}",
                      "short": true,
                      "value": "issue url: ${{ github.event.issue.html_url }}"
                    }
                  ]
                }
              ]
            }