name: matrix
on: push
jobs:
    get-matrix: # job name
        startegy: 
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                version: [12,14] 
        runs-on: ${{ matrix.os }}
        steps:
        - name: check matrix
          run: |
            echo ${{matrix.os}}
            echo ${{matrix.version}}