name: tag-filter
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # ex) v1.0.0 or 2.2.2 /

jobs:
  tag-filter-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello
